server:
  servlet:
    context-path: /
  port: ${PORT:8080}

keycloak:
  public-url: ${KC_PUBLIC_URL:http://192.168.0.198:9090/realms/notes}
  admin:
    url: ${KC_API_URL:http://localhost:9090}
    userRealm: ${KC_USERS_REALM:notes}
    adminRealm: ${KC_ADMIN_REALM:master}
    username: ${KC_API_USERNAME:backend}
    password: ${KC_API_PASSWORD:password}
    client-id: ${KC_API_CLIENT_ID:admin-cli}

logging:
  level:
    ROOT: INFO

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notes}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      maximum-pool-size: ${DB_CONNECTION_POOL_SIZE:10}
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.public-url}
          jwk-set-uri: ${keycloak.public-url}/protocol/openid-connect/certs

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://192.168.0.198:3000}

security:
  api-key: ${API_KEY:notes}
  api-key-header: X-API-KEY

springdoc:
  api-docs:
    path: ${management.endpoints.web.base-path}/docs
  swagger-ui:
    path: ${management.endpoints.web.base-path}/swagger-ui
    urls:
      - url: ${server.servlet.context-path}openapi/specification.yaml
        name: API

management:
  endpoints:
    web:
      base-path: /api/system
      exposure:
        include: info,health,prometheus
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
info:
  app:
    build_version: ${BUILD_VERSION:undefined}


