ingress:
  enabled: true
  ingressClassName: nginx
  pathType: ImplementationSpecific
  hostname: auth.dev.zametki.online
  path: /
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

replicaCount: 1

resources:
  limits:
    memory: 3Gi
    cpu: 2000m
  requests:
    cpu: 2000m
    memory: 2Gi
