openapi: 3.0.0
info:
  title: Document Management API
  version: 1.0.0

servers:
  - url: ""
    description: API base path

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponseDTO:
      oneOf:
        - $ref: '#/components/schemas/ServerErrorDTO'
        - $ref: '#/components/schemas/AuthErrorDTO'
        - $ref: '#/components/schemas/NotFoundErrorDTO'
        - $ref: '#/components/schemas/BadRequestErrorDTO'
        - $ref: '#/components/schemas/DomainErrorDTO'

    ServerErrorDTO:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum: [SERVER_ERROR]
          example: SERVER_ERROR
        message:
          type: string
          example: "Internal server error occurred"

    NotFoundErrorDTO:
      type: object
      required:
        - type
        - details
      properties:
        type:
          type: string
          enum: [NOT_FOUND_ERROR]
          example: NOT_FOUND_ERROR
        details:
          type: object
          required:
            - objectType
            - key
          properties:
            objectType:
              type: string
              example: document
            key:
              type: string
              example: "123"

    BadRequestErrorDTO:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum: [BAD_REQUEST]
          example: BAD_REQUEST
        message:
          type: string
          example: "Invalid request format"

    AuthErrorDTO:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum: [ AUTH_ERROR ]
          example: AUTH_ERROR
        message:
          type: string
          example: "Invalid access token"

    DomainErrorDTO:
      type: object
      required:
        - type
        - code
      properties:
        type:
          type: string
          enum: [DOMAIN_ERROR]
          example: DOMAIN_ERROR
        message:
          type: string
          example: "You are not the owner of this document"
        details:
          type: object
          additionalProperties: true

  responses:
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorDTO'

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundErrorDTO'

    AuthError:
      description: authentication or authorization error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthErrorDTO'

    BadRequestError:
      description: Invalid request format
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestErrorDTO'

    DefaultError:
      description: Default error response
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ServerErrorDTO'
              - $ref: '#/components/schemas/AuthErrorDTO'
              - $ref: '#/components/schemas/BadRequestErrorDTO'
              - $ref: '#/components/schemas/NotFoundErrorDTO'
              - $ref: '#/components/schemas/DomainErrorDTO'

paths:

  /greeting:
    get:
      operationId: getGreeting
      tags: [Greeting]
      summary: Get greeting
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Greeting
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'