ingresses:
  - className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: api.dev.tpl.palsergech.tech
        paths:
          - path: /bc(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: 'api.dev.tpl.palsergech.tech-tls'
        hosts:
          - 'api.dev.tpl.palsergech.tech'

resources:
  limits:
    cpu: 700m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 400Mi
