{{- $fullName := include "msvc.fullname" $ -}}
{{- range $_, $ing := $.Values.ingresses }}
---
{{- $svcPort := $ing.port | default $.Values.service.ports.http -}}
{{- if and $.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $ing.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ing.annotations "kubernetes.io/ingress.class" $ing.className }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- if $ing.name }}
  name: {{ $fullName }}-{{ $ing.name }}
  {{- else }}
  name: {{ $fullName }}
  {{- end }}
  labels:
    {{- include "msvc.labels" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
      {{- include "msvc.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with $ing.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or $.Values.commonAnnotations $ing.annotations }}
  annotations:
    {{- with $ing.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.commonAnnotations }}
      {{- include "msvc.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ing.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ing.className }}
  {{- end }}
  {{- if $ing.tls }}
  tls:
    {{- range $ing.tls }}
    - secretName: {{ .secretName }}
      {{- if .hosts }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ing.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ (.service).name | default $fullName }}
                port:
                  number: {{ (.service).port | default $svcPort }}
              {{- else }}
              serviceName: {{ (.service).name | default $fullName }}
              servicePort: {{ (.service).port | default $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
