ingress:
  enabled: true
  ingressClassName: nginx
  pathType: ImplementationSpecific
  hostname: auth.dev.tpl.palsergech.tech
  path: /
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

extraEnvVars:
  - name: KC_HTTP_METRICS_SLOS
    value: "250"
  - name: KC_HTTP_METRICS_HISTOGRAMS_ENABLED
    value: "true"

replicaCount: 1

resources:
  limits:
    cpu: 6
    memory: 3Gi
  requests:
    cpu: 300m
    memory: 2Gi
