ingress:
  enabled: true
  ingressClassName: nginx
  pathType: ImplementationSpecific
  hostname: auth.dev.tpl.palsergech.tech
  path: /
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 3Gi
  requests:
    cpu: 300m
    memory: 2Gi
